name: 'Tiny Tapeout Formal Equivalence test'
description: 'This action will prove that the GL netlist is equivalent to the RTL using YosysHQ eqy tool'
branding:
  color: orange
  icon: check

inputs:
  flow:
    description: 'Flow used for hardening the chip'
    default: 'openlane1'
    required: false
    type: choice
    options:
      - openlane1
      - openlane2

runs:
  using: 'composite'
  steps:
    - name: Download GDS artifact
      uses: actions/download-artifact@v4
      with:
        name: GDS

    - name: Set up environment variables
      shell: bash
      run: |
        cat << EOF >> $GITHUB_ENV
        PDK_ROOT=/home/runner/pdk
        PDK=sky130A
        EOF

    - name: Install Sky130 PDK
      uses: TinyTapeout/volare-action@v2
      with:
        pdk_name: sky130
        pdk_version: cd1748bb197f9b7af62a54507de6624e30363943
        pdk_root: /home/runner/pdk

    # install oss fpga tools
    - name: install oss-cad-suite
      uses: YosysHQ/setup-oss-cad-suite@v2
      with:
          python-override: true

    # for debugging, show all the files
    - name: show files
      shell: bash
      run: |
        pwd
        which eqy
        find .

    - name: test
      shell: bash
      env:
        FLOW: ${{ inputs.flow }}
      run: |
        pwd
        cp ~/work/_temp/oss-cad-suite/examples/eqy/spm/formal_pdk_proc.py src/
        if [ "$FLOW" == "openlane1" ]
        then
          cp runs/wokwi/results/final/verilog/gl/*.nl.v src/gate_level_netlist.v
        elif [ "$FLOW" == "openlane2" ]
        then
          cp runs/wokwi/final/nl/*.nl.v src/gate_level_netlist.v
        fi
        cd src
        cp $PDK_ROOT/sky130A/libs.ref/sky130_fd_sc_hd/verilog/primitives.v primitives.v
        cp $PDK_ROOT/sky130A/libs.ref/sky130_fd_sc_hd/verilog/sky130_fd_sc_hd.v sky130_fd_sc_hd.v
        eqy -f equivalence.eqy
