name: 'Tiny Tapeout Custom GDS Action'
description: 'This action builds prepares a custom GDS project for submitting to Tiny Tapeout'
branding:
  color: purple
  icon: layers

inputs:
  top_module:
    description: 'The name of the top module (e.g. tt_um_example)'
    required: true
  gds_path:
    description: 'Path to the GDS file'
    required: true
  lef_path:
    description: 'Path to the LEF file'
    required: true
  verilog_path:
    description: 'Path to the verilog GL netlist (optional)'
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Create commit_id.json
      shell: bash
      run: |
        mkdir -p tt_submission
        jq -n \
          --arg app "custom_gds action" \
          --arg repo "${{ github.server_url }}/${{ github.repository }}" \
          --arg commit "${{ github.sha }}" \
          --arg workflow_url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          '{app: $app, repo: $repo, commit: $commit, workflow_url: $workflow_url}' \
          > tt_submission/commit_id.json

    - name: Copy GDS / LEF files to tt_submission
      shell: bash
      run: |
        cp ${{ inputs.gds_path }} tt_submission/${{ inputs.top_module }}.gds
        cp ${{ inputs.lef_path }} tt_submission/${{ inputs.top_module }}.lef
        
        touch tt_submission/${{ inputs.top_module }}.v
        if [ -n "${{ inputs.verilog_path }}" ]; then
          cp ${{ inputs.verilog_path }} tt_submission/${{ inputs.top_module }}.v
        fi

    - name: Publish tt_submission artifact
      uses: actions/upload-artifact@v4
      with:
        name: tt_submission
        path: |
          info.yaml
          LICENSE
          docs/*
          tt_submission/*

    # Install packages for 'Render PNG from GDS' step:
    - name: Install prerequisites
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: librsvg2-bin pngquant # librsvg2-bin for rsvg-convert; pngquant for heavy PNG compression.
        version: tt07

    - name: Checkout tt-support-tools repo
      uses: actions/checkout@v4
      with:
        repository: tinytapeout/tt-support-tools
        path: tt
        ref: tt07

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip' # caching pip dependencies

    - name: Install tt-support-tools dependencies
      shell: bash
      run: pip install -r tt/requirements.txt

    - name: Render PNG from GDS
      shell: bash
      run: './tt/tt_tool.py --create-png 2>&1 || echo "WARNING: Failed to render PNG preview from GDS; error $?"'
      env:
        GDS_PATH: ${{ inputs.gds_path }}

    - name: Upload gds_render (png) artifact
      uses: actions/upload-artifact@v4
      with:
        name: gds_render
        path: 'gds_render.png'
