name: 'Tiny Tapeout Precheck'
description: 'This action runs DRC checks on the user projects prior to submission'
branding:
  color: purple
  icon: eye

inputs:
  tools-repo:
    description: 'Override tt-support-tools repository'
    default: 'TinyTapeout/tt-support-tools'
    required: false
    type: string
  tools-ref:
    description: 'Override tt-support-tools branch/tag/commit'
    default: 'main'
    required: false
    type: string

runs:
  using: 'composite'
  steps:
    - name: Checkout tt-support-tools repo
      uses: actions/checkout@v4
      with:
        repository: '${{ inputs.tools-repo }}'
        path: tt
        ref: '${{ inputs.tools-ref }}'

    - name: Download GDS artifact
      uses: actions/download-artifact@v4
      with:
        name: tt_submission

    - name: Set up environment variables
      working-directory: tt_submission
      shell: bash
      run: |
        # Defaults
        PDK=$(jq -r '.PDK' pdk.json)
        PDK_ROOT=/home/runner/pdk
        PDK_SOURCE=$(jq -r '.PDK_SOURCE' pdk.json)
        PDK_VERSION=$(jq -r '.PDK_VERSION' pdk.json)
        USE_CIEL=1

        # PDK-specific overrides
        if [ "$PDK" == "gf180mcuD" ] && [ -n "$PDK_VERSION" ]; then
          PDK_VERSION="ff08c23db8359afce3f134c454e7930586d0641c"
        elif [ "$PDK" == "ihp-sg13g2" ]; then
          PDK_ROOT=$GITHUB_WORKSPACE/pdk
          USE_CIEL=0
        elif [ "$PDK" == "sky130A" ] && [ -n "$PDK_VERSION" ]; then
          PDK_VERSION="0536d02d875c8f67dd7cca3902ac457e62f20005"
        fi

        cat << __EOF >> $GITHUB_ENV
        PDK=$PDK
        PDK_ROOT=$PDK_ROOT
        PDK_SOURCE=$PDK_SOURCE
        PDK_VERSION=$PDK_VERSION
        USE_CIEL=$USE_CIEL
        __EOF

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      shell: bash
      working-directory: tt/precheck
      run: pip install -r requirements.txt

    - name: Install ${{ env.PDK }} PDK
      if: ${{ env.USE_CIEL == '1' }}
      uses: TinyTapeout/ciel-action@v1
      with:
        pdk_name: ${{ env.PDK }}
        pdk_version: ${{ env.PDK_VERSION }}
        pdk_root: ${{ env.PDK_ROOT }}

    - name: Checkout IHP PDK repo
      if: ${{ env.PDK == 'ihp-sg13g2' }}
      uses: actions/checkout@v4
      with:
        repository: 'TinyTapeout/IHP-Open-PDK'
        ref: 'tt2025'
        path: ${{ env.PDK_ROOT }}

    - name: Install Nix
      uses: rikhuijzer/cache-install@v1.1.4
      with:
        key: nix-${{ hashFiles('precheck/default.nix') }}
        nix_file: 'tt/precheck/default.nix'

    - name: Build Nix packages
      shell: bash
      working-directory: tt/precheck
      run: nix-build

    - name: Run precheck
      shell: bash
      working-directory: tt/precheck
      run: nix-shell --run "python precheck.py --gds ${{ github.workspace }}/tt_submission/*.gds* --tech ${{ env.PDK }}"

    - name: Test Summary
      uses: test-summary/action@v2.3
      with:
        paths: 'tt/precheck/reports/results.xml'
      if: always()

    - name: Capture test results
      shell: bash
      working-directory: tt/precheck
      if: always()
      run: cat reports/results.md >> $GITHUB_STEP_SUMMARY

    - name: Upload reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: precheck_reports
        path: tt/precheck/reports
