name: 'Tiny Tapeout Viewer Action'
description: 'This action create a 3D model of your Tiny Tapeout project'
branding:
  color: purple
  icon: eye

inputs:
  pdk:
    description: 'PDK used for rendering the 3D viewer'
    default: 'ihp'
    type: choice
    options:
      - 'sky130'
      - 'ihp'

runs:
  using: 'composite'
  steps:
    - name: Download GDS artifact
      uses: actions/download-artifact@v4
      with:
        name: tt_submission

    - name: Set up environment variables
      shell: bash
      run: |
        PDK_CHOICE="${{ inputs.pdk }}"
        if [ "$PDK_CHOICE" == "sky130" ]; then
          echo "PROCESS=SKY130" >> $GITHUB_ENV
        elif [ "$PDK_CHOICE" == "ihp" ]; then
          echo "PROCESS=SG13G2" >> $GITHUB_ENV
        fi

    - name: Download gds_render (png) artifact
      uses: actions/download-artifact@v4
      with:
        name: gds_render
        path: gh-pages

    - name: Copy OAS And GDSII
      shell: bash
      run: |
        cp tt_submission/*.gds gh-pages/tinytapeout.gds
        cp tt_submission/*.oas gh-pages/tinytapeout.oas

    - name: Generate an HTML page that redirects to viewer
      shell: bash
      run: |
        cat << EOF >> gh-pages/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Redirecting to 3D Viewer...</title>
          </head>
          <body>
            <script>
              location.href = "https://gds-viewer.tinytapeout.com/?process=${{ env.PROCESS }}&model=" + encodeURIComponent(location.href + '/tinytapeout.oas');
            </script>
          </body>
          </html>
        EOF

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'gh-pages'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Check for failure
      if: failure()
      shell: bash
      run: |
        echo "Failed to deploy to GitHub Pages, please follow the link to troubleshoot: https://tinytapeout.com/faq/#my-github-action-is-failing-on-the-pages-part"

        cat << EOF >> $GITHUB_STEP_SUMMARY
        # Error
        Failed to deploy to GitHub Pages. [Click here for instructions how to fix](https://tinytapeout.com/faq/#my-github-action-is-failing-on-the-pages-part).
        EOF

        exit 1

    - name: Display preview in workflow summary
      shell: bash
      run: |
        PAGE_URL=${{ steps.deployment.outputs.page_url }}
        PAGE_URL=$(echo "$PAGE_URL" | sed -e 's/\/$//')
        cat << EOF >> $GITHUB_STEP_SUMMARY
        # 3D Viewer
        [Open 3D viewer](https://gds-viewer.tinytapeout.com/?model=$PAGE_URL/tinytapeout.oas&process=${{ env.PROCESS }})

        # 2D Preview
        ![png]($PAGE_URL/gds_render.png)
        EOF
