name: 'Tiny Tapeout Viewer Action'
description: 'This action create a 3D model of your Tiny Tapeout project'
branding:
  color: purple
  icon: eye

runs:
  using: 'composite'
  steps:
    - name: Checkout GDS2glTF repo
      uses: actions/checkout@v4
      with:
        repository: mbalestrini/GDS2glTF

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip' # caching pip dependencies

    - name: Download GDS artifact
      uses: actions/download-artifact@v4
      with:
        name: tt_submission

    - name: Download gds_render (png) artifact
      uses: actions/download-artifact@v4
      with:
        name: gds_render
        path: gh-pages

    - name: gds2gltf
      shell: bash
      run: |
        python -m pip install numpy gdspy triangle pygltflib
        cp tt_submission/*.gds tinytapeout.gds
        python3 gds2gltf.py tinytapeout.gds
        cp tinytapeout.gds.gltf gh-pages/tinytapeout.gds.gltf

    - name: Generate HTML pages that redirects to viewer
      shell: bash
      run: |
        cat << EOF >> gh-pages/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Redirecting to GDS Viewer...</title>
          </head>
          <body>
            <script>
              location.href = "https://gds-viewer.tinytapeout.com/?model=" + encodeURIComponent(location.href + '/tinytapeout.gds.gltf');
            </script>
          </body>
          </html>
        EOF

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'gh-pages'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Check for failure
      if: failure()
      run: |
        echo "Failed to deploy to GitHub Pages, please follow the link to troubleshoot: https://tinytapeout.com/faq/#my-github-action-is-failing-on-the-pages-part"

        cat << EOF >> $GITHUB_STEP_SUMMARY
        # Error
        Failed to deploy to GitHub Pages. [Click here for instructions how to fix](https://tinytapeout.com/faq/#my-github-action-is-failing-on-the-pages-part).
        EOF

        exit 1

    - name: Display preview in workflow summary
      shell: bash
      run: |
        PAGE_URL=${{ steps.deployment.outputs.page_url }}
        PAGE_URL=$(echo "$PAGE_URL" | sed -e 's/\/$//')
        cat << EOF >> $GITHUB_STEP_SUMMARY
        # 3D Viewer
        [open 3D viewer](https://gds-viewer.tinytapeout.com/?model=$PAGE_URL/tinytapeout.gds.gltf)

        # 2D Preview
        ![png]($PAGE_URL/gds_render.png)
        EOF
