name: 'Tiny Tapeout Docs Action'
description: 'This action create the documentation of your Tiny Tapeout project'
branding:
  color: purple
  icon: book-open

inputs:
  tools-repo:
    description: 'Override tt-support-tools repository'
    default: 'TinyTapeout/tt-support-tools'
    required: false
    type: string
  tools-ref:
    description: 'Override tt-support-tools branch/tag/commit'
    default: 'tt09'
    required: false
    type: string

runs:
  using: 'composite'
  steps:
    - name: Checkout tt-support-tools repo
      uses: actions/checkout@v4
      with:
        repository: "${{ inputs.tools-repo }}"
        path: tt
        ref: "${{ inputs.tools-ref }}"

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip' # caching pip dependencies
    - shell: bash
      run: pip install -r tt/requirements.txt

    - name: Install Pandoc & ghdl
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y pandoc texlive-xetex librsvg2-bin ghdl-llvm

    - name: Check docs (info.yaml)
      shell: bash
      run: ./tt/tt_tool.py --check-docs

    - name: Create PDF
      shell: bash
      run: ./tt/tt_tool.py --create-pdf

    - name: Archive PDF
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: datasheet.pdf
