name: 'Tiny Tapeout Gate Level test'
description: 'This action will copy the GL netlist from the GDS action and run your testbench on it'
branding:
  color: purple
  icon: check
inputs:
  test-dir:
    description: 'The directory with the Makefile for running the tests'
    required: true
    default: 'src'

runs:
  using: 'composite'
  steps:
    - name: Download GDS artifact
      uses: actions/download-artifact@v3
      with:
        name: GDS

    - name: Set up environment variables
      shell: bash
      run: |
        cat << EOF >> $GITHUB_ENV
        PDK_ROOT=/home/runner/pdk
        PDK=sky130A
        EOF

    - name: Install Sky130 PDK
      uses: TinyTapeout/volare-action@v1
      with:
        pdk_name: sky130
        pdk_version: 1341f54f5ce0c4955326297f235e4ace1eb6d419
        pdk_root: /home/runner/pdk

    # for debugging, show all the files
    - name: show files
      shell: bash
      run: |
        pwd
        find .

    # Set Python up and install cocotb
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: install cocotb
      shell: bash
      run: pip install cocotb==1.8.0

    - name: install iverilog
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y iverilog

    - name: test
      shell: bash
      run: |
        pwd
        rm runs/wokwi/results/final/verilog/gl/*.nl.v 
        cp runs/wokwi/results/final/verilog/gl/*.v "${{ inputs.test-dir }}/gate_level_netlist.v"
        cd "${{ inputs.test-dir }}"
        make clean
        GATES=yes make
        # make will return success even if the test fails, so check for failure in the results.xml
        ! grep failure results.xml

    - name: upload vcd
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
          name: gatelevel-test-vcd
          path: ${{ inputs.test-dir }}/tb.vcd
